// Generated by gencpp from file image_segmentation_skill_msgs/ImageSegmentationSkillFeedback.msg
// DO NOT EDIT!


#ifndef IMAGE_SEGMENTATION_SKILL_MSGS_MESSAGE_IMAGESEGMENTATIONSKILLFEEDBACK_H
#define IMAGE_SEGMENTATION_SKILL_MSGS_MESSAGE_IMAGESEGMENTATIONSKILLFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace image_segmentation_skill_msgs
{
template <class ContainerAllocator>
struct ImageSegmentationSkillFeedback_
{
  typedef ImageSegmentationSkillFeedback_<ContainerAllocator> Type;

  ImageSegmentationSkillFeedback_()
    : percentage(0)
    , skillStatus()  {
    }
  ImageSegmentationSkillFeedback_(const ContainerAllocator& _alloc)
    : percentage(0)
    , skillStatus(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _percentage_type;
  _percentage_type percentage;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _skillStatus_type;
  _skillStatus_type skillStatus;





  typedef boost::shared_ptr< ::image_segmentation_skill_msgs::ImageSegmentationSkillFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::image_segmentation_skill_msgs::ImageSegmentationSkillFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct ImageSegmentationSkillFeedback_

typedef ::image_segmentation_skill_msgs::ImageSegmentationSkillFeedback_<std::allocator<void> > ImageSegmentationSkillFeedback;

typedef boost::shared_ptr< ::image_segmentation_skill_msgs::ImageSegmentationSkillFeedback > ImageSegmentationSkillFeedbackPtr;
typedef boost::shared_ptr< ::image_segmentation_skill_msgs::ImageSegmentationSkillFeedback const> ImageSegmentationSkillFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::image_segmentation_skill_msgs::ImageSegmentationSkillFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::image_segmentation_skill_msgs::ImageSegmentationSkillFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::image_segmentation_skill_msgs::ImageSegmentationSkillFeedback_<ContainerAllocator1> & lhs, const ::image_segmentation_skill_msgs::ImageSegmentationSkillFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.percentage == rhs.percentage &&
    lhs.skillStatus == rhs.skillStatus;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::image_segmentation_skill_msgs::ImageSegmentationSkillFeedback_<ContainerAllocator1> & lhs, const ::image_segmentation_skill_msgs::ImageSegmentationSkillFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace image_segmentation_skill_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::image_segmentation_skill_msgs::ImageSegmentationSkillFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::image_segmentation_skill_msgs::ImageSegmentationSkillFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::image_segmentation_skill_msgs::ImageSegmentationSkillFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::image_segmentation_skill_msgs::ImageSegmentationSkillFeedback_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::image_segmentation_skill_msgs::ImageSegmentationSkillFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::image_segmentation_skill_msgs::ImageSegmentationSkillFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::image_segmentation_skill_msgs::ImageSegmentationSkillFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "679659a5e7bd72a0f86fdd2a666e4c40";
  }

  static const char* value(const ::image_segmentation_skill_msgs::ImageSegmentationSkillFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x679659a5e7bd72a0ULL;
  static const uint64_t static_value2 = 0xf86fdd2a666e4c40ULL;
};

template<class ContainerAllocator>
struct DataType< ::image_segmentation_skill_msgs::ImageSegmentationSkillFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "image_segmentation_skill_msgs/ImageSegmentationSkillFeedback";
  }

  static const char* value(const ::image_segmentation_skill_msgs::ImageSegmentationSkillFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::image_segmentation_skill_msgs::ImageSegmentationSkillFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"#####################\n"
"# Feedback definition\n"
"int32 percentage\n"
"string skillStatus\n"
;
  }

  static const char* value(const ::image_segmentation_skill_msgs::ImageSegmentationSkillFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::image_segmentation_skill_msgs::ImageSegmentationSkillFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.percentage);
      stream.next(m.skillStatus);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ImageSegmentationSkillFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::image_segmentation_skill_msgs::ImageSegmentationSkillFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::image_segmentation_skill_msgs::ImageSegmentationSkillFeedback_<ContainerAllocator>& v)
  {
    s << indent << "percentage: ";
    Printer<int32_t>::stream(s, indent + "  ", v.percentage);
    s << indent << "skillStatus: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.skillStatus);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IMAGE_SEGMENTATION_SKILL_MSGS_MESSAGE_IMAGESEGMENTATIONSKILLFEEDBACK_H
