// Generated by gencpp from file image_segmentation_skill_msgs/ImageSegmentationSkillActionGoal.msg
// DO NOT EDIT!


#ifndef IMAGE_SEGMENTATION_SKILL_MSGS_MESSAGE_IMAGESEGMENTATIONSKILLACTIONGOAL_H
#define IMAGE_SEGMENTATION_SKILL_MSGS_MESSAGE_IMAGESEGMENTATIONSKILLACTIONGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <actionlib_msgs/GoalID.h>
#include <image_segmentation_skill_msgs/ImageSegmentationSkillGoal.h>

namespace image_segmentation_skill_msgs
{
template <class ContainerAllocator>
struct ImageSegmentationSkillActionGoal_
{
  typedef ImageSegmentationSkillActionGoal_<ContainerAllocator> Type;

  ImageSegmentationSkillActionGoal_()
    : header()
    , goal_id()
    , goal()  {
    }
  ImageSegmentationSkillActionGoal_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , goal_id(_alloc)
    , goal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::actionlib_msgs::GoalID_<ContainerAllocator>  _goal_id_type;
  _goal_id_type goal_id;

   typedef  ::image_segmentation_skill_msgs::ImageSegmentationSkillGoal_<ContainerAllocator>  _goal_type;
  _goal_type goal;





  typedef boost::shared_ptr< ::image_segmentation_skill_msgs::ImageSegmentationSkillActionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::image_segmentation_skill_msgs::ImageSegmentationSkillActionGoal_<ContainerAllocator> const> ConstPtr;

}; // struct ImageSegmentationSkillActionGoal_

typedef ::image_segmentation_skill_msgs::ImageSegmentationSkillActionGoal_<std::allocator<void> > ImageSegmentationSkillActionGoal;

typedef boost::shared_ptr< ::image_segmentation_skill_msgs::ImageSegmentationSkillActionGoal > ImageSegmentationSkillActionGoalPtr;
typedef boost::shared_ptr< ::image_segmentation_skill_msgs::ImageSegmentationSkillActionGoal const> ImageSegmentationSkillActionGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::image_segmentation_skill_msgs::ImageSegmentationSkillActionGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::image_segmentation_skill_msgs::ImageSegmentationSkillActionGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::image_segmentation_skill_msgs::ImageSegmentationSkillActionGoal_<ContainerAllocator1> & lhs, const ::image_segmentation_skill_msgs::ImageSegmentationSkillActionGoal_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.goal_id == rhs.goal_id &&
    lhs.goal == rhs.goal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::image_segmentation_skill_msgs::ImageSegmentationSkillActionGoal_<ContainerAllocator1> & lhs, const ::image_segmentation_skill_msgs::ImageSegmentationSkillActionGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace image_segmentation_skill_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::image_segmentation_skill_msgs::ImageSegmentationSkillActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::image_segmentation_skill_msgs::ImageSegmentationSkillActionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::image_segmentation_skill_msgs::ImageSegmentationSkillActionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::image_segmentation_skill_msgs::ImageSegmentationSkillActionGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::image_segmentation_skill_msgs::ImageSegmentationSkillActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::image_segmentation_skill_msgs::ImageSegmentationSkillActionGoal_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::image_segmentation_skill_msgs::ImageSegmentationSkillActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6f1a5b9ff7f03bccb26b3e74cc7e4491";
  }

  static const char* value(const ::image_segmentation_skill_msgs::ImageSegmentationSkillActionGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6f1a5b9ff7f03bccULL;
  static const uint64_t static_value2 = 0xb26b3e74cc7e4491ULL;
};

template<class ContainerAllocator>
struct DataType< ::image_segmentation_skill_msgs::ImageSegmentationSkillActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "image_segmentation_skill_msgs/ImageSegmentationSkillActionGoal";
  }

  static const char* value(const ::image_segmentation_skill_msgs::ImageSegmentationSkillActionGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::image_segmentation_skill_msgs::ImageSegmentationSkillActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalID goal_id\n"
"ImageSegmentationSkillGoal goal\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalID\n"
"# The stamp should store the time at which this goal was requested.\n"
"# It is used by an action server when it tries to preempt all\n"
"# goals that were requested before a certain time\n"
"time stamp\n"
"\n"
"# The id provides a way to associate feedback and\n"
"# result message with specific goal requests. The id\n"
"# specified must be unique.\n"
"string id\n"
"\n"
"\n"
"================================================================================\n"
"MSG: image_segmentation_skill_msgs/ImageSegmentationSkillGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#################\n"
"# Goal definition\n"
"string detection_model\n"
"uint32 operation_mode\n"
;
  }

  static const char* value(const ::image_segmentation_skill_msgs::ImageSegmentationSkillActionGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::image_segmentation_skill_msgs::ImageSegmentationSkillActionGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.goal_id);
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ImageSegmentationSkillActionGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::image_segmentation_skill_msgs::ImageSegmentationSkillActionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::image_segmentation_skill_msgs::ImageSegmentationSkillActionGoal_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "goal_id: ";
    s << std::endl;
    Printer< ::actionlib_msgs::GoalID_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_id);
    s << indent << "goal: ";
    s << std::endl;
    Printer< ::image_segmentation_skill_msgs::ImageSegmentationSkillGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IMAGE_SEGMENTATION_SKILL_MSGS_MESSAGE_IMAGESEGMENTATIONSKILLACTIONGOAL_H
