ros_verbosity_level: 'DEBUG'
action_server_name: 'ImageSegmentationSkill'
debug_tools: True #desactivate to speed up
device_GPU: False
filters: False
image_resolution: 512
output_resolution:
  width: 2064
  height: 1544
deep_learning_library: 'tensorflow'
