// Generated by gencpp from file dope_skill_msgs/DopeSkillResult.msg
// DO NOT EDIT!


#ifndef DOPE_SKILL_MSGS_MESSAGE_DOPESKILLRESULT_H
#define DOPE_SKILL_MSGS_MESSAGE_DOPESKILLRESULT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/TransformStamped.h>

namespace dope_skill_msgs
{
template <class ContainerAllocator>
struct DopeSkillResult_
{
  typedef DopeSkillResult_<ContainerAllocator> Type;

  DopeSkillResult_()
    : percentage(0)
    , skillStatus()
    , outcome()
    , pose()  {
    }
  DopeSkillResult_(const ContainerAllocator& _alloc)
    : percentage(0)
    , skillStatus(_alloc)
    , outcome(_alloc)
    , pose(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _percentage_type;
  _percentage_type percentage;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _skillStatus_type;
  _skillStatus_type skillStatus;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _outcome_type;
  _outcome_type outcome;

   typedef  ::geometry_msgs::TransformStamped_<ContainerAllocator>  _pose_type;
  _pose_type pose;





  typedef boost::shared_ptr< ::dope_skill_msgs::DopeSkillResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dope_skill_msgs::DopeSkillResult_<ContainerAllocator> const> ConstPtr;

}; // struct DopeSkillResult_

typedef ::dope_skill_msgs::DopeSkillResult_<std::allocator<void> > DopeSkillResult;

typedef boost::shared_ptr< ::dope_skill_msgs::DopeSkillResult > DopeSkillResultPtr;
typedef boost::shared_ptr< ::dope_skill_msgs::DopeSkillResult const> DopeSkillResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dope_skill_msgs::DopeSkillResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dope_skill_msgs::DopeSkillResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dope_skill_msgs::DopeSkillResult_<ContainerAllocator1> & lhs, const ::dope_skill_msgs::DopeSkillResult_<ContainerAllocator2> & rhs)
{
  return lhs.percentage == rhs.percentage &&
    lhs.skillStatus == rhs.skillStatus &&
    lhs.outcome == rhs.outcome &&
    lhs.pose == rhs.pose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dope_skill_msgs::DopeSkillResult_<ContainerAllocator1> & lhs, const ::dope_skill_msgs::DopeSkillResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dope_skill_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dope_skill_msgs::DopeSkillResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dope_skill_msgs::DopeSkillResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dope_skill_msgs::DopeSkillResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dope_skill_msgs::DopeSkillResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dope_skill_msgs::DopeSkillResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dope_skill_msgs::DopeSkillResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dope_skill_msgs::DopeSkillResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "60064ae4a52afa51a106b96d5b760708";
  }

  static const char* value(const ::dope_skill_msgs::DopeSkillResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x60064ae4a52afa51ULL;
  static const uint64_t static_value2 = 0xa106b96d5b760708ULL;
};

template<class ContainerAllocator>
struct DataType< ::dope_skill_msgs::DopeSkillResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dope_skill_msgs/DopeSkillResult";
  }

  static const char* value(const ::dope_skill_msgs::DopeSkillResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dope_skill_msgs::DopeSkillResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#result definition\n"
"int32 percentage\n"
"string skillStatus\n"
"string outcome\n"
"geometry_msgs/TransformStamped pose\n"
"\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/TransformStamped\n"
"# This expresses a transform from coordinate frame header.frame_id\n"
"# to the coordinate frame child_frame_id\n"
"#\n"
"# This message is mostly used by the \n"
"# <a href=\"http://wiki.ros.org/tf\">tf</a> package. \n"
"# See its documentation for more information.\n"
"\n"
"Header header\n"
"string child_frame_id # the frame id of the child frame\n"
"Transform transform\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Transform\n"
"# This represents the transform between two coordinate frames in free space.\n"
"\n"
"Vector3 translation\n"
"Quaternion rotation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::dope_skill_msgs::DopeSkillResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dope_skill_msgs::DopeSkillResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.percentage);
      stream.next(m.skillStatus);
      stream.next(m.outcome);
      stream.next(m.pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DopeSkillResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dope_skill_msgs::DopeSkillResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dope_skill_msgs::DopeSkillResult_<ContainerAllocator>& v)
  {
    s << indent << "percentage: ";
    Printer<int32_t>::stream(s, indent + "  ", v.percentage);
    s << indent << "skillStatus: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.skillStatus);
    s << indent << "outcome: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.outcome);
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::TransformStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DOPE_SKILL_MSGS_MESSAGE_DOPESKILLRESULT_H
