// Generated by gencpp from file dope_skill_msgs/DopeSkillAction.msg
// DO NOT EDIT!


#ifndef DOPE_SKILL_MSGS_MESSAGE_DOPESKILLACTION_H
#define DOPE_SKILL_MSGS_MESSAGE_DOPESKILLACTION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <dope_skill_msgs/DopeSkillActionGoal.h>
#include <dope_skill_msgs/DopeSkillActionResult.h>
#include <dope_skill_msgs/DopeSkillActionFeedback.h>

namespace dope_skill_msgs
{
template <class ContainerAllocator>
struct DopeSkillAction_
{
  typedef DopeSkillAction_<ContainerAllocator> Type;

  DopeSkillAction_()
    : action_goal()
    , action_result()
    , action_feedback()  {
    }
  DopeSkillAction_(const ContainerAllocator& _alloc)
    : action_goal(_alloc)
    , action_result(_alloc)
    , action_feedback(_alloc)  {
  (void)_alloc;
    }



   typedef  ::dope_skill_msgs::DopeSkillActionGoal_<ContainerAllocator>  _action_goal_type;
  _action_goal_type action_goal;

   typedef  ::dope_skill_msgs::DopeSkillActionResult_<ContainerAllocator>  _action_result_type;
  _action_result_type action_result;

   typedef  ::dope_skill_msgs::DopeSkillActionFeedback_<ContainerAllocator>  _action_feedback_type;
  _action_feedback_type action_feedback;





  typedef boost::shared_ptr< ::dope_skill_msgs::DopeSkillAction_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dope_skill_msgs::DopeSkillAction_<ContainerAllocator> const> ConstPtr;

}; // struct DopeSkillAction_

typedef ::dope_skill_msgs::DopeSkillAction_<std::allocator<void> > DopeSkillAction;

typedef boost::shared_ptr< ::dope_skill_msgs::DopeSkillAction > DopeSkillActionPtr;
typedef boost::shared_ptr< ::dope_skill_msgs::DopeSkillAction const> DopeSkillActionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dope_skill_msgs::DopeSkillAction_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dope_skill_msgs::DopeSkillAction_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dope_skill_msgs::DopeSkillAction_<ContainerAllocator1> & lhs, const ::dope_skill_msgs::DopeSkillAction_<ContainerAllocator2> & rhs)
{
  return lhs.action_goal == rhs.action_goal &&
    lhs.action_result == rhs.action_result &&
    lhs.action_feedback == rhs.action_feedback;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dope_skill_msgs::DopeSkillAction_<ContainerAllocator1> & lhs, const ::dope_skill_msgs::DopeSkillAction_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dope_skill_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dope_skill_msgs::DopeSkillAction_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dope_skill_msgs::DopeSkillAction_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dope_skill_msgs::DopeSkillAction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dope_skill_msgs::DopeSkillAction_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dope_skill_msgs::DopeSkillAction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dope_skill_msgs::DopeSkillAction_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dope_skill_msgs::DopeSkillAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "51583c0750c4d437a8642ed73ca6d099";
  }

  static const char* value(const ::dope_skill_msgs::DopeSkillAction_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x51583c0750c4d437ULL;
  static const uint64_t static_value2 = 0xa8642ed73ca6d099ULL;
};

template<class ContainerAllocator>
struct DataType< ::dope_skill_msgs::DopeSkillAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dope_skill_msgs/DopeSkillAction";
  }

  static const char* value(const ::dope_skill_msgs::DopeSkillAction_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dope_skill_msgs::DopeSkillAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"DopeSkillActionGoal action_goal\n"
"DopeSkillActionResult action_result\n"
"DopeSkillActionFeedback action_feedback\n"
"\n"
"================================================================================\n"
"MSG: dope_skill_msgs/DopeSkillActionGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalID goal_id\n"
"DopeSkillGoal goal\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalID\n"
"# The stamp should store the time at which this goal was requested.\n"
"# It is used by an action server when it tries to preempt all\n"
"# goals that were requested before a certain time\n"
"time stamp\n"
"\n"
"# The id provides a way to associate feedback and\n"
"# result message with specific goal requests. The id\n"
"# specified must be unique.\n"
"string id\n"
"\n"
"\n"
"================================================================================\n"
"MSG: dope_skill_msgs/DopeSkillGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#goal definition\n"
"int32 operation_mode\n"
"string model_name\n"
"string object_name\n"
"\n"
"================================================================================\n"
"MSG: dope_skill_msgs/DopeSkillActionResult\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalStatus status\n"
"DopeSkillResult result\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalStatus\n"
"GoalID goal_id\n"
"uint8 status\n"
"uint8 PENDING         = 0   # The goal has yet to be processed by the action server\n"
"uint8 ACTIVE          = 1   # The goal is currently being processed by the action server\n"
"uint8 PREEMPTED       = 2   # The goal received a cancel request after it started executing\n"
"                            #   and has since completed its execution (Terminal State)\n"
"uint8 SUCCEEDED       = 3   # The goal was achieved successfully by the action server (Terminal State)\n"
"uint8 ABORTED         = 4   # The goal was aborted during execution by the action server due\n"
"                            #    to some failure (Terminal State)\n"
"uint8 REJECTED        = 5   # The goal was rejected by the action server without being processed,\n"
"                            #    because the goal was unattainable or invalid (Terminal State)\n"
"uint8 PREEMPTING      = 6   # The goal received a cancel request after it started executing\n"
"                            #    and has not yet completed execution\n"
"uint8 RECALLING       = 7   # The goal received a cancel request before it started executing,\n"
"                            #    but the action server has not yet confirmed that the goal is canceled\n"
"uint8 RECALLED        = 8   # The goal received a cancel request before it started executing\n"
"                            #    and was successfully cancelled (Terminal State)\n"
"uint8 LOST            = 9   # An action client can determine that a goal is LOST. This should not be\n"
"                            #    sent over the wire by an action server\n"
"\n"
"#Allow for the user to associate a string with GoalStatus for debugging\n"
"string text\n"
"\n"
"\n"
"================================================================================\n"
"MSG: dope_skill_msgs/DopeSkillResult\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#result definition\n"
"int32 percentage\n"
"string skillStatus\n"
"string outcome\n"
"geometry_msgs/TransformStamped pose\n"
"\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/TransformStamped\n"
"# This expresses a transform from coordinate frame header.frame_id\n"
"# to the coordinate frame child_frame_id\n"
"#\n"
"# This message is mostly used by the \n"
"# <a href=\"http://wiki.ros.org/tf\">tf</a> package. \n"
"# See its documentation for more information.\n"
"\n"
"Header header\n"
"string child_frame_id # the frame id of the child frame\n"
"Transform transform\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Transform\n"
"# This represents the transform between two coordinate frames in free space.\n"
"\n"
"Vector3 translation\n"
"Quaternion rotation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: dope_skill_msgs/DopeSkillActionFeedback\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalStatus status\n"
"DopeSkillFeedback feedback\n"
"\n"
"================================================================================\n"
"MSG: dope_skill_msgs/DopeSkillFeedback\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#feedback\n"
"int32 percentage\n"
"string skillStatus\n"
"\n"
;
  }

  static const char* value(const ::dope_skill_msgs::DopeSkillAction_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dope_skill_msgs::DopeSkillAction_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.action_goal);
      stream.next(m.action_result);
      stream.next(m.action_feedback);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DopeSkillAction_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dope_skill_msgs::DopeSkillAction_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dope_skill_msgs::DopeSkillAction_<ContainerAllocator>& v)
  {
    s << indent << "action_goal: ";
    s << std::endl;
    Printer< ::dope_skill_msgs::DopeSkillActionGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.action_goal);
    s << indent << "action_result: ";
    s << std::endl;
    Printer< ::dope_skill_msgs::DopeSkillActionResult_<ContainerAllocator> >::stream(s, indent + "  ", v.action_result);
    s << indent << "action_feedback: ";
    s << std::endl;
    Printer< ::dope_skill_msgs::DopeSkillActionFeedback_<ContainerAllocator> >::stream(s, indent + "  ", v.action_feedback);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DOPE_SKILL_MSGS_MESSAGE_DOPESKILLACTION_H
