// Auto-generated. Do not edit!

// (in-package image_segmentation_skill_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class ImageSegmentationSkillGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.detection_model = null;
      this.operation_mode = null;
    }
    else {
      if (initObj.hasOwnProperty('detection_model')) {
        this.detection_model = initObj.detection_model
      }
      else {
        this.detection_model = '';
      }
      if (initObj.hasOwnProperty('operation_mode')) {
        this.operation_mode = initObj.operation_mode
      }
      else {
        this.operation_mode = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type ImageSegmentationSkillGoal
    // Serialize message field [detection_model]
    bufferOffset = _serializer.string(obj.detection_model, buffer, bufferOffset);
    // Serialize message field [operation_mode]
    bufferOffset = _serializer.uint32(obj.operation_mode, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type ImageSegmentationSkillGoal
    let len;
    let data = new ImageSegmentationSkillGoal(null);
    // Deserialize message field [detection_model]
    data.detection_model = _deserializer.string(buffer, bufferOffset);
    // Deserialize message field [operation_mode]
    data.operation_mode = _deserializer.uint32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += _getByteLength(object.detection_model);
    return length + 8;
  }

  static datatype() {
    // Returns string type for a message object
    return 'image_segmentation_skill_msgs/ImageSegmentationSkillGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '69dc3d6e4c7e6e89a60d1b5eb79bf88b';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #################
    # Goal definition
    string detection_model
    uint32 operation_mode
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new ImageSegmentationSkillGoal(null);
    if (msg.detection_model !== undefined) {
      resolved.detection_model = msg.detection_model;
    }
    else {
      resolved.detection_model = ''
    }

    if (msg.operation_mode !== undefined) {
      resolved.operation_mode = msg.operation_mode;
    }
    else {
      resolved.operation_mode = 0
    }

    return resolved;
    }
};

module.exports = ImageSegmentationSkillGoal;
