// Auto-generated. Do not edit!

// (in-package image_segmentation_skill_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;
let MaskDefinition = require('./MaskDefinition.js');

//-----------------------------------------------------------

class ImageSegmentationSkillResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.percentage = null;
      this.skillStatus = null;
      this.outcome = null;
      this.mask_pub = null;
    }
    else {
      if (initObj.hasOwnProperty('percentage')) {
        this.percentage = initObj.percentage
      }
      else {
        this.percentage = 0;
      }
      if (initObj.hasOwnProperty('skillStatus')) {
        this.skillStatus = initObj.skillStatus
      }
      else {
        this.skillStatus = '';
      }
      if (initObj.hasOwnProperty('outcome')) {
        this.outcome = initObj.outcome
      }
      else {
        this.outcome = '';
      }
      if (initObj.hasOwnProperty('mask_pub')) {
        this.mask_pub = initObj.mask_pub
      }
      else {
        this.mask_pub = new MaskDefinition();
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type ImageSegmentationSkillResult
    // Serialize message field [percentage]
    bufferOffset = _serializer.int32(obj.percentage, buffer, bufferOffset);
    // Serialize message field [skillStatus]
    bufferOffset = _serializer.string(obj.skillStatus, buffer, bufferOffset);
    // Serialize message field [outcome]
    bufferOffset = _serializer.string(obj.outcome, buffer, bufferOffset);
    // Serialize message field [mask_pub]
    bufferOffset = MaskDefinition.serialize(obj.mask_pub, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type ImageSegmentationSkillResult
    let len;
    let data = new ImageSegmentationSkillResult(null);
    // Deserialize message field [percentage]
    data.percentage = _deserializer.int32(buffer, bufferOffset);
    // Deserialize message field [skillStatus]
    data.skillStatus = _deserializer.string(buffer, bufferOffset);
    // Deserialize message field [outcome]
    data.outcome = _deserializer.string(buffer, bufferOffset);
    // Deserialize message field [mask_pub]
    data.mask_pub = MaskDefinition.deserialize(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += _getByteLength(object.skillStatus);
    length += _getByteLength(object.outcome);
    length += MaskDefinition.getMessageSize(object.mask_pub);
    return length + 12;
  }

  static datatype() {
    // Returns string type for a message object
    return 'image_segmentation_skill_msgs/ImageSegmentationSkillResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'aaab811457c594f5592825b0e0a9f167';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    
    ###################
    # Result definition
    
    #sensor_msgs/PointCloud2 cloud
    int32 percentage
    string skillStatus
    string outcome
    image_segmentation_skill_msgs/MaskDefinition mask_pub
    
    ================================================================================
    MSG: image_segmentation_skill_msgs/MaskDefinition
    int32 instance_nr
    std_msgs/Float32MultiArray scores
    sensor_msgs/Image mask_image
    ================================================================================
    MSG: std_msgs/Float32MultiArray
    # Please look at the MultiArrayLayout message definition for
    # documentation on all multiarrays.
    
    MultiArrayLayout  layout        # specification of data layout
    float32[]         data          # array of data
    
    
    ================================================================================
    MSG: std_msgs/MultiArrayLayout
    # The multiarray declares a generic multi-dimensional array of a
    # particular data type.  Dimensions are ordered from outer most
    # to inner most.
    
    MultiArrayDimension[] dim # Array of dimension properties
    uint32 data_offset        # padding elements at front of data
    
    # Accessors should ALWAYS be written in terms of dimension stride
    # and specified outer-most dimension first.
    # 
    # multiarray(i,j,k) = data[data_offset + dim_stride[1]*i + dim_stride[2]*j + k]
    #
    # A standard, 3-channel 640x480 image with interleaved color channels
    # would be specified as:
    #
    # dim[0].label  = "height"
    # dim[0].size   = 480
    # dim[0].stride = 3*640*480 = 921600  (note dim[0] stride is just size of image)
    # dim[1].label  = "width"
    # dim[1].size   = 640
    # dim[1].stride = 3*640 = 1920
    # dim[2].label  = "channel"
    # dim[2].size   = 3
    # dim[2].stride = 3
    #
    # multiarray(i,j,k) refers to the ith row, jth column, and kth channel.
    
    ================================================================================
    MSG: std_msgs/MultiArrayDimension
    string label   # label of given dimension
    uint32 size    # size of given dimension (in type units)
    uint32 stride  # stride of given dimension
    ================================================================================
    MSG: sensor_msgs/Image
    # This message contains an uncompressed image
    # (0, 0) is at top-left corner of image
    #
    
    Header header        # Header timestamp should be acquisition time of image
                         # Header frame_id should be optical frame of camera
                         # origin of frame should be optical center of camera
                         # +x should point to the right in the image
                         # +y should point down in the image
                         # +z should point into to plane of the image
                         # If the frame_id here and the frame_id of the CameraInfo
                         # message associated with the image conflict
                         # the behavior is undefined
    
    uint32 height         # image height, that is, number of rows
    uint32 width          # image width, that is, number of columns
    
    # The legal values for encoding are in file src/image_encodings.cpp
    # If you want to standardize a new string format, join
    # ros-users@lists.sourceforge.net and send an email proposing a new encoding.
    
    string encoding       # Encoding of pixels -- channel meaning, ordering, size
                          # taken from the list of strings in include/sensor_msgs/image_encodings.h
    
    uint8 is_bigendian    # is this data bigendian?
    uint32 step           # Full row length in bytes
    uint8[] data          # actual matrix data, size is (step * rows)
    
    ================================================================================
    MSG: std_msgs/Header
    # Standard metadata for higher-level stamped data types.
    # This is generally used to communicate timestamped data 
    # in a particular coordinate frame.
    # 
    # sequence ID: consecutively increasing ID 
    uint32 seq
    #Two-integer timestamp that is expressed as:
    # * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
    # * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
    # time-handling sugar is provided by the client library
    time stamp
    #Frame this data is associated with
    string frame_id
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new ImageSegmentationSkillResult(null);
    if (msg.percentage !== undefined) {
      resolved.percentage = msg.percentage;
    }
    else {
      resolved.percentage = 0
    }

    if (msg.skillStatus !== undefined) {
      resolved.skillStatus = msg.skillStatus;
    }
    else {
      resolved.skillStatus = ''
    }

    if (msg.outcome !== undefined) {
      resolved.outcome = msg.outcome;
    }
    else {
      resolved.outcome = ''
    }

    if (msg.mask_pub !== undefined) {
      resolved.mask_pub = MaskDefinition.Resolve(msg.mask_pub)
    }
    else {
      resolved.mask_pub = new MaskDefinition()
    }

    return resolved;
    }
};

module.exports = ImageSegmentationSkillResult;
