// Auto-generated. Do not edit!

// (in-package image_segmentation_skill_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class ImageSegmentationSkillFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.percentage = null;
      this.skillStatus = null;
    }
    else {
      if (initObj.hasOwnProperty('percentage')) {
        this.percentage = initObj.percentage
      }
      else {
        this.percentage = 0;
      }
      if (initObj.hasOwnProperty('skillStatus')) {
        this.skillStatus = initObj.skillStatus
      }
      else {
        this.skillStatus = '';
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type ImageSegmentationSkillFeedback
    // Serialize message field [percentage]
    bufferOffset = _serializer.int32(obj.percentage, buffer, bufferOffset);
    // Serialize message field [skillStatus]
    bufferOffset = _serializer.string(obj.skillStatus, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type ImageSegmentationSkillFeedback
    let len;
    let data = new ImageSegmentationSkillFeedback(null);
    // Deserialize message field [percentage]
    data.percentage = _deserializer.int32(buffer, bufferOffset);
    // Deserialize message field [skillStatus]
    data.skillStatus = _deserializer.string(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += _getByteLength(object.skillStatus);
    return length + 8;
  }

  static datatype() {
    // Returns string type for a message object
    return 'image_segmentation_skill_msgs/ImageSegmentationSkillFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '679659a5e7bd72a0f86fdd2a666e4c40';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    
    #####################
    # Feedback definition
    int32 percentage
    string skillStatus
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new ImageSegmentationSkillFeedback(null);
    if (msg.percentage !== undefined) {
      resolved.percentage = msg.percentage;
    }
    else {
      resolved.percentage = 0
    }

    if (msg.skillStatus !== undefined) {
      resolved.skillStatus = msg.skillStatus;
    }
    else {
      resolved.skillStatus = ''
    }

    return resolved;
    }
};

module.exports = ImageSegmentationSkillFeedback;
