(cl:defpackage image_segmentation_skill_msgs-msg
  (:use )
  (:export
   "<IMAGESEGMENTATIONSKILLACTION>"
   "IMAGESEGMENTATIONSKILLACTION"
   "<IMAGESEGMENTATIONSKILLACTIONFEEDBACK>"
   "IMAGESEGMENTATIONSKILLACTIONFEEDBACK"
   "<IMAGESEGMENTATIONSKILLACTIONGOAL>"
   "IMAGESEGMENTATIONSKILLACTIONGOAL"
   "<IMAGESEGMENTATIONSKILLACTIONRESULT>"
   "IMAGESEGMENTATIONSKILLACTIONRESULT"
   "<IMAGESEGMENTATIONSKILLFEEDBACK>"
   "IMAGESEGMENTATIONSKILLFEEDBACK"
   "<IMAGESEGMENTATIONSKILLGOAL>"
   "IMAGESEGMENTATIONSKILLGOAL"
   "<IMAGESEGMENTATIONSKILLRESULT>"
   "IMAGESEGMENTATIONSKILLRESULT"
   "<MASKDEFINITION>"
   "MASKDEFINITION"
  ))

