(cl:defpackage dope_skill_msgs-msg
  (:use )
  (:export
   "<DOPESKILLACTION>"
   "DOPESKILLACTION"
   "<DOPESKILLACTIONFEEDBACK>"
   "DOPESKILLACTIONFEEDBACK"
   "<DOPESKILLACTIONGOAL>"
   "DOPESKILLACTIONGOAL"
   "<DOPESKILLACTIONRESULT>"
   "DOPESKILLACTIONRESULT"
   "<DOPESKILLFEEDBACK>"
   "DOPESKILLFEEDBACK"
   "<DOPESKILLGOAL>"
   "DOPESKILLGOAL"
   "<DOPESKILLRESULT>"
   "DOPESKILLRESULT"
  ))

